#!/bin/bash
echo "═══════════════════════════════════════════════════════"
echo "  🔥  BRATUCHA TERMUX - QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  startpage      → Interaktives Menü (Alle Tools)"
echo "  writer / w     → Writer Tool (120+ Commands)"
echo "  launcher       → Tool Launcher (29 Tools)"
echo "  dashboard      → Web UI (Port 8080)"
echo "  auto-update    → Alles aktualisieren"
echo "  system-tune    → System Tuning"
echo "  lazymux        → 800+ Tools Installer"
echo "  wolkansec      → 354 Security Tools"
echo "  m4t01          → 380+ Tools Launcher"
echo "  pyphisher      → Social Engineering"
echo "  metasploit     → Security Framework"
echo "  nethunter      → Kali for Android"
echo "  install-all    → Alle Tools installieren"
echo "  test-all       → Alle Tools testen"
echo "  push-gh        → Git push zu GitHub"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  GitHub: github.com/xxxyalaxx90xxx/termux-tools"
echo "═══════════════════════════════════════════════════════"
