# Skeleton build.sh script for new package.

TERMUX_PKG_HOMEPAGE=
TERMUX_PKG_DESCRIPTION=""
TERMUX_PKG_LICENSE=""
TERMUX_PKG_MAINTAINER="@author-repository"
TERMUX_PKG_VERSION=
TERMUX_PKG_SRCURL=
TERMUX_PKG_SHA256=
#TERMUX_PKG_DEPENDS=""
#TERMUX_PKG_BUILD_IN_SRC=true
